command:
  - uvicorn
  - backend.main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: CATALOG_NAME
    value: "goalpost_catalog"
  - name: SCHEMA_NAME
    value: "goalpost"
  - name: WAREHOUSE_ID
    value: "08a07bafc8924aaa"
  - name: LLM_ENDPOINT
    value: "vjsendpoint1"
  - name: DEBUG
    value: "false"
