command:
  - uvicorn
  - backend.main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  # Unity Catalog name (e.g., "goalpost_catalog", "main", "your_catalog")
  - name: CATALOG_NAME
    value: ""
  # Schema name within the catalog
  - name: SCHEMA_NAME
    value: "goalpost"
  # SQL Warehouse ID (e.g., "abc123def456")
  - name: WAREHOUSE_ID
    value: ""
  # LLM Serving Endpoint name (e.g., "databricks-claude-haiku-4-5", "databricks-meta-llama-3-1-70b-instruct")
  - name: LLM_ENDPOINT
    value: ""
  - name: DEBUG
    value: "false"
